<?php if ($this->getInstallmentAmount()) : ?>
<script type="text/javascript">
    var laybuyConfig = <?php echo json_encode($this->getInstallmentsConfig()) ?>;
</script>
<div id="laybuy-modal" class="laybuy-popup-modal">
    <div id="laybuy-popup-outer">
        <div class="laybuy-popup-modal-content">
            <iframe src="<?php echo Mage::helper('laybuy')->getPopupIframeSrc() ?>"></iframe>
            <span class="close">&times;</span>
        </div>
    </div>
</div>
<?php endif; ?>